/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConfigSetApplyConfiguration represents an declarative configuration of the ConfigSet type for use
// with apply.
type ConfigSetApplyConfiguration struct {
	Section *string `json:"section,omitempty"`
	Key     *string `json:"key,omitempty"`
	Value   *string `json:"value,omitempty"`
}

// ConfigSetApplyConfiguration constructs an declarative configuration of the ConfigSet type for use with
// apply.
func ConfigSet() *ConfigSetApplyConfiguration {
	return &ConfigSetApplyConfiguration{}
}

// WithSection sets the Section field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Section field is set to the value of the last call.
func (b *ConfigSetApplyConfiguration) WithSection(value string) *ConfigSetApplyConfiguration {
	b.Section = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ConfigSetApplyConfiguration) WithKey(value string) *ConfigSetApplyConfiguration {
	b.Key = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ConfigSetApplyConfiguration) WithValue(value string) *ConfigSetApplyConfiguration {
	b.Value = &value
	return b
}
