/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExternalSecretInfoApplyConfiguration represents an declarative configuration of the ExternalSecretInfo type for use
// with apply.
type ExternalSecretInfoApplyConfiguration struct {
	Organization *string `json:"organization,omitempty"`
	RootSecret   *string `json:"root_secret,omitempty"`
}

// ExternalSecretInfoApplyConfiguration constructs an declarative configuration of the ExternalSecretInfo type for use with
// apply.
func ExternalSecretInfo() *ExternalSecretInfoApplyConfiguration {
	return &ExternalSecretInfoApplyConfiguration{}
}

// WithOrganization sets the Organization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Organization field is set to the value of the last call.
func (b *ExternalSecretInfoApplyConfiguration) WithOrganization(value string) *ExternalSecretInfoApplyConfiguration {
	b.Organization = &value
	return b
}

// WithRootSecret sets the RootSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootSecret field is set to the value of the last call.
func (b *ExternalSecretInfoApplyConfiguration) WithRootSecret(value string) *ExternalSecretInfoApplyConfiguration {
	b.RootSecret = &value
	return b
}
