/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// K8sServiceApplyConfiguration represents an declarative configuration of the K8sService type for use
// with apply.
type K8sServiceApplyConfiguration struct {
	Type                     *string `json:"type,omitempty"`
	PublishNotReadyAddresses *bool   `json:"publish_not_ready_addresses,omitempty"`
}

// K8sServiceApplyConfiguration constructs an declarative configuration of the K8sService type for use with
// apply.
func K8sService() *K8sServiceApplyConfiguration {
	return &K8sServiceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *K8sServiceApplyConfiguration) WithType(value string) *K8sServiceApplyConfiguration {
	b.Type = &value
	return b
}

// WithPublishNotReadyAddresses sets the PublishNotReadyAddresses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishNotReadyAddresses field is set to the value of the last call.
func (b *K8sServiceApplyConfiguration) WithPublishNotReadyAddresses(value bool) *K8sServiceApplyConfiguration {
	b.PublishNotReadyAddresses = &value
	return b
}
