/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UnitsetSpecApplyConfiguration represents an declarative configuration of the UnitsetSpec type for use
// with apply.
type UnitsetSpecApplyConfiguration struct {
	Secret            *string `json:"secret,omitempty"`
	MainContainerName *string `json:"mainContainerName,omitempty"`
	MainImageVersion  *string `json:"mainImageVersion,omitempty"`
	UnService         *bool   `json:"unService,omitempty"`
	UnBindNode        *bool   `json:"unBindNode,omitempty"`
}

// UnitsetSpecApplyConfiguration constructs an declarative configuration of the UnitsetSpec type for use with
// apply.
func UnitsetSpec() *UnitsetSpecApplyConfiguration {
	return &UnitsetSpecApplyConfiguration{}
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *UnitsetSpecApplyConfiguration) WithSecret(value string) *UnitsetSpecApplyConfiguration {
	b.Secret = &value
	return b
}

// WithMainContainerName sets the MainContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainContainerName field is set to the value of the last call.
func (b *UnitsetSpecApplyConfiguration) WithMainContainerName(value string) *UnitsetSpecApplyConfiguration {
	b.MainContainerName = &value
	return b
}

// WithMainImageVersion sets the MainImageVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainImageVersion field is set to the value of the last call.
func (b *UnitsetSpecApplyConfiguration) WithMainImageVersion(value string) *UnitsetSpecApplyConfiguration {
	b.MainImageVersion = &value
	return b
}

// WithUnService sets the UnService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnService field is set to the value of the last call.
func (b *UnitsetSpecApplyConfiguration) WithUnService(value bool) *UnitsetSpecApplyConfiguration {
	b.UnService = &value
	return b
}

// WithUnBindNode sets the UnBindNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnBindNode field is set to the value of the last call.
func (b *UnitsetSpecApplyConfiguration) WithUnBindNode(value bool) *UnitsetSpecApplyConfiguration {
	b.UnBindNode = &value
	return b
}
