/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UnitsetStatusApplyConfiguration represents an declarative configuration of the UnitsetStatus type for use
// with apply.
type UnitsetStatusApplyConfiguration struct {
	Units      *int `json:"units,omitempty"`
	ReadyUnits *int `json:"readyUnits,omitempty"`
}

// UnitsetStatusApplyConfiguration constructs an declarative configuration of the UnitsetStatus type for use with
// apply.
func UnitsetStatus() *UnitsetStatusApplyConfiguration {
	return &UnitsetStatusApplyConfiguration{}
}

// WithUnits sets the Units field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Units field is set to the value of the last call.
func (b *UnitsetStatusApplyConfiguration) WithUnits(value int) *UnitsetStatusApplyConfiguration {
	b.Units = &value
	return b
}

// WithReadyUnits sets the ReadyUnits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyUnits field is set to the value of the last call.
func (b *UnitsetStatusApplyConfiguration) WithReadyUnits(value int) *UnitsetStatusApplyConfiguration {
	b.ReadyUnits = &value
	return b
}
