/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// VolumeRequirementApplyConfiguration represents an declarative configuration of the VolumeRequirement type for use
// with apply.
type VolumeRequirementApplyConfiguration struct {
	Capacity  *resource.Quantity `json:"capacity,omitempty"`
	Type      *string            `json:"type,omitempty"`
	MountPath *string            `json:"mount_path,omitempty"`
}

// VolumeRequirementApplyConfiguration constructs an declarative configuration of the VolumeRequirement type for use with
// apply.
func VolumeRequirement() *VolumeRequirementApplyConfiguration {
	return &VolumeRequirementApplyConfiguration{}
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *VolumeRequirementApplyConfiguration) WithCapacity(value resource.Quantity) *VolumeRequirementApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *VolumeRequirementApplyConfiguration) WithType(value string) *VolumeRequirementApplyConfiguration {
	b.Type = &value
	return b
}

// WithMountPath sets the MountPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPath field is set to the value of the last call.
func (b *VolumeRequirementApplyConfiguration) WithMountPath(value string) *VolumeRequirementApplyConfiguration {
	b.MountPath = &value
	return b
}
