/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "upm-pkg/pkg/apis/unit/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUnits implements UnitInterface
type FakeUnits struct {
	Fake *FakeUnitV1alpha1
	ns   string
}

var unitsResource = schema.GroupVersionResource{Group: "unit.bsgchina.com", Version: "v1alpha1", Resource: "units"}

var unitsKind = schema.GroupVersionKind{Group: "unit.bsgchina.com", Version: "v1alpha1", Kind: "Unit"}

// Get takes name of the unit, and returns the corresponding unit object, and an error if there is any.
func (c *FakeUnits) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Unit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(unitsResource, c.ns, name), &v1alpha1.Unit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Unit), err
}

// List takes label and field selectors, and returns the list of Units that match those selectors.
func (c *FakeUnits) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(unitsResource, unitsKind, c.ns, opts), &v1alpha1.UnitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.UnitList{ListMeta: obj.(*v1alpha1.UnitList).ListMeta}
	for _, item := range obj.(*v1alpha1.UnitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested units.
func (c *FakeUnits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(unitsResource, c.ns, opts))

}

// Create takes the representation of a unit and creates it.  Returns the server's representation of the unit, and an error, if there is any.
func (c *FakeUnits) Create(ctx context.Context, unit *v1alpha1.Unit, opts v1.CreateOptions) (result *v1alpha1.Unit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(unitsResource, c.ns, unit), &v1alpha1.Unit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Unit), err
}

// Update takes the representation of a unit and updates it. Returns the server's representation of the unit, and an error, if there is any.
func (c *FakeUnits) Update(ctx context.Context, unit *v1alpha1.Unit, opts v1.UpdateOptions) (result *v1alpha1.Unit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(unitsResource, c.ns, unit), &v1alpha1.Unit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Unit), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUnits) UpdateStatus(ctx context.Context, unit *v1alpha1.Unit, opts v1.UpdateOptions) (*v1alpha1.Unit, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(unitsResource, "status", c.ns, unit), &v1alpha1.Unit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Unit), err
}

// Delete takes name of the unit and deletes it. Returns an error if one occurs.
func (c *FakeUnits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(unitsResource, c.ns, name), &v1alpha1.Unit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUnits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(unitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.UnitList{})
	return err
}

// Patch applies the patch and returns the patched unit.
func (c *FakeUnits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Unit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(unitsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Unit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Unit), err
}
