/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ActionApplyConfiguration represents an declarative configuration of the Action type for use
// with apply.
type ActionApplyConfiguration struct {
	Rebuild           *RebuildActionApplyConfiguration           `json:"rebuild,omitempty"`
	Migrate           *MigrateActionApplyConfiguration           `json:"migrate,omitempty"`
	ReuseRetainVolume *ReuseRetainVolumeActionApplyConfiguration `json:"reuse_retain_volume,omitempty"`
}

// ActionApplyConfiguration constructs an declarative configuration of the Action type for use with
// apply.
func Action() *ActionApplyConfiguration {
	return &ActionApplyConfiguration{}
}

// WithRebuild sets the Rebuild field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rebuild field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithRebuild(value *RebuildActionApplyConfiguration) *ActionApplyConfiguration {
	b.Rebuild = value
	return b
}

// WithMigrate sets the Migrate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Migrate field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithMigrate(value *MigrateActionApplyConfiguration) *ActionApplyConfiguration {
	b.Migrate = value
	return b
}

// WithReuseRetainVolume sets the ReuseRetainVolume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReuseRetainVolume field is set to the value of the last call.
func (b *ActionApplyConfiguration) WithReuseRetainVolume(value *ReuseRetainVolumeActionApplyConfiguration) *ActionApplyConfiguration {
	b.ReuseRetainVolume = value
	return b
}
