/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "tesseract/pkg/apis/unit/v1alpha1"
)

// NetworkingRequestApplyConfiguration represents an declarative configuration of the NetworkingRequest type for use
// with apply.
type NetworkingRequestApplyConfiguration struct {
	Mode      *v1alpha1.NetworkModeType `json:"mode,omitempty"`
	Bandwidth *int32                    `json:"bandwidth,omitempty"`
	Network   *string                   `json:"network,omitempty"`
	Type      *v1alpha1.NetworkType     `json:"type,omitempty"`
}

// NetworkingRequestApplyConfiguration constructs an declarative configuration of the NetworkingRequest type for use with
// apply.
func NetworkingRequest() *NetworkingRequestApplyConfiguration {
	return &NetworkingRequestApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *NetworkingRequestApplyConfiguration) WithMode(value v1alpha1.NetworkModeType) *NetworkingRequestApplyConfiguration {
	b.Mode = &value
	return b
}

// WithBandwidth sets the Bandwidth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bandwidth field is set to the value of the last call.
func (b *NetworkingRequestApplyConfiguration) WithBandwidth(value int32) *NetworkingRequestApplyConfiguration {
	b.Bandwidth = &value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *NetworkingRequestApplyConfiguration) WithNetwork(value string) *NetworkingRequestApplyConfiguration {
	b.Network = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *NetworkingRequestApplyConfiguration) WithType(value v1alpha1.NetworkType) *NetworkingRequestApplyConfiguration {
	b.Type = &value
	return b
}
