/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RebuildVolumeStatusApplyConfiguration represents an declarative configuration of the RebuildVolumeStatus type for use
// with apply.
type RebuildVolumeStatusApplyConfiguration struct {
	RetainVolumeSuffix *int `json:"retain_volume_suffix,omitempty"`
	CurVolumeSuffix    *int `json:"cur_volume_suffix,omitempty"`
}

// RebuildVolumeStatusApplyConfiguration constructs an declarative configuration of the RebuildVolumeStatus type for use with
// apply.
func RebuildVolumeStatus() *RebuildVolumeStatusApplyConfiguration {
	return &RebuildVolumeStatusApplyConfiguration{}
}

// WithRetainVolumeSuffix sets the RetainVolumeSuffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetainVolumeSuffix field is set to the value of the last call.
func (b *RebuildVolumeStatusApplyConfiguration) WithRetainVolumeSuffix(value int) *RebuildVolumeStatusApplyConfiguration {
	b.RetainVolumeSuffix = &value
	return b
}

// WithCurVolumeSuffix sets the CurVolumeSuffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurVolumeSuffix field is set to the value of the last call.
func (b *RebuildVolumeStatusApplyConfiguration) WithCurVolumeSuffix(value int) *RebuildVolumeStatusApplyConfiguration {
	b.CurVolumeSuffix = &value
	return b
}
