/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// StorageApplyConfiguration represents an declarative configuration of the Storage type for use
// with apply.
type StorageApplyConfiguration struct {
	Type       *string                  `json:"type,omitempty"`
	Level      *string                  `json:"level,omitempty"`
	AllocType  *string                  `json:"allocType,omitempty"`
	FsType     *string                  `json:"fsType,omitempty"`
	Mounter    *string                  `json:"mounter,omitempty"`
	Request    *resource.Quantity       `json:"request,omitempty"`
	VolumeMode *v1.PersistentVolumeMode `json:"volumeMode,omitempty"`
}

// StorageApplyConfiguration constructs an declarative configuration of the Storage type for use with
// apply.
func Storage() *StorageApplyConfiguration {
	return &StorageApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithType(value string) *StorageApplyConfiguration {
	b.Type = &value
	return b
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithLevel(value string) *StorageApplyConfiguration {
	b.Level = &value
	return b
}

// WithAllocType sets the AllocType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocType field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithAllocType(value string) *StorageApplyConfiguration {
	b.AllocType = &value
	return b
}

// WithFsType sets the FsType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FsType field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithFsType(value string) *StorageApplyConfiguration {
	b.FsType = &value
	return b
}

// WithMounter sets the Mounter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mounter field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithMounter(value string) *StorageApplyConfiguration {
	b.Mounter = &value
	return b
}

// WithRequest sets the Request field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Request field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithRequest(value resource.Quantity) *StorageApplyConfiguration {
	b.Request = &value
	return b
}

// WithVolumeMode sets the VolumeMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeMode field is set to the value of the last call.
func (b *StorageApplyConfiguration) WithVolumeMode(value v1.PersistentVolumeMode) *StorageApplyConfiguration {
	b.VolumeMode = &value
	return b
}
