/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// UnitSpecApplyConfiguration represents an declarative configuration of the UnitSpec type for use
// with apply.
type UnitSpecApplyConfiguration struct {
	Action               *ActionApplyConfiguration  `json:"action,omitempty"`
	MainContainerName    *string                    `json:"mainContainerName,omitempty"`
	MainImageVersion     *string                    `json:"mainImageVersion,omitempty"`
	UnService            *bool                      `json:"unService,omitempty"`
	UnBindNode           *bool                      `json:"unBindNode,omitempty"`
	Volumes              []v1.Volume                `json:"volumes,omitempty"`
	VolumeClaimTemplates []v1.PersistentVolumeClaim `json:"volumeClaimTemplates,omitempty"`
	VolumeMounts         []v1.VolumeMount           `json:"volumeMounts,omitempty"`
	Template             *v1.PodTemplateSpec        `json:"template,omitempty"`
}

// UnitSpecApplyConfiguration constructs an declarative configuration of the UnitSpec type for use with
// apply.
func UnitSpec() *UnitSpecApplyConfiguration {
	return &UnitSpecApplyConfiguration{}
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithAction(value *ActionApplyConfiguration) *UnitSpecApplyConfiguration {
	b.Action = value
	return b
}

// WithMainContainerName sets the MainContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainContainerName field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithMainContainerName(value string) *UnitSpecApplyConfiguration {
	b.MainContainerName = &value
	return b
}

// WithMainImageVersion sets the MainImageVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MainImageVersion field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithMainImageVersion(value string) *UnitSpecApplyConfiguration {
	b.MainImageVersion = &value
	return b
}

// WithUnService sets the UnService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnService field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithUnService(value bool) *UnitSpecApplyConfiguration {
	b.UnService = &value
	return b
}

// WithUnBindNode sets the UnBindNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnBindNode field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithUnBindNode(value bool) *UnitSpecApplyConfiguration {
	b.UnBindNode = &value
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *UnitSpecApplyConfiguration) WithVolumes(values ...v1.Volume) *UnitSpecApplyConfiguration {
	for i := range values {
		b.Volumes = append(b.Volumes, values[i])
	}
	return b
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *UnitSpecApplyConfiguration) WithVolumeClaimTemplates(values ...v1.PersistentVolumeClaim) *UnitSpecApplyConfiguration {
	for i := range values {
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, values[i])
	}
	return b
}

// WithVolumeMounts adds the given value to the VolumeMounts field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeMounts field.
func (b *UnitSpecApplyConfiguration) WithVolumeMounts(values ...v1.VolumeMount) *UnitSpecApplyConfiguration {
	for i := range values {
		b.VolumeMounts = append(b.VolumeMounts, values[i])
	}
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *UnitSpecApplyConfiguration) WithTemplate(value v1.PodTemplateSpec) *UnitSpecApplyConfiguration {
	b.Template = &value
	return b
}
