/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	unitv1alpha1 "tesseract/pkg/apis/unit/v1alpha1"
)

// UnitStatusApplyConfiguration represents an declarative configuration of the UnitStatus type for use
// with apply.
type UnitStatusApplyConfiguration struct {
	RebuildStatus *RebuildVolumeStatusApplyConfiguration `json:"volume_suffix,omitempty"`
	Conditions    []unitv1alpha1.Condition               `json:"conditions,omitempty"`
	ErrMessages   []ErrMsgApplyConfiguration             `json:"err_messages,omitempty"`
}

// UnitStatusApplyConfiguration constructs an declarative configuration of the UnitStatus type for use with
// apply.
func UnitStatus() *UnitStatusApplyConfiguration {
	return &UnitStatusApplyConfiguration{}
}

// WithRebuildStatus sets the RebuildStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RebuildStatus field is set to the value of the last call.
func (b *UnitStatusApplyConfiguration) WithRebuildStatus(value *RebuildVolumeStatusApplyConfiguration) *UnitStatusApplyConfiguration {
	b.RebuildStatus = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *UnitStatusApplyConfiguration) WithConditions(values ...unitv1alpha1.Condition) *UnitStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}

// WithErrMessages adds the given value to the ErrMessages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ErrMessages field.
func (b *UnitStatusApplyConfiguration) WithErrMessages(values ...*ErrMsgApplyConfiguration) *UnitStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithErrMessages")
		}
		b.ErrMessages = append(b.ErrMessages, *values[i])
	}
	return b
}
